package lime.graphics.bgfx;

enum abstract BGFXTopologySort(Int) from Int to Int
{
	var DIRECTION_FRONT_TO_BACK_MIN = 0;
	var DIRECTION_FRONT_TO_BACK_AVG = 1;
	var DIRECTION_FRONT_TO_BACK_MAX = 2;
	var DIRECTION_BACK_TO_FRONT_MIN = 3;
	var DIRECTION_BACK_TO_FRONT_AVG = 4;
	var DIRECTION_BACK_TO_FRONT_MAX = 5;
	var DISTANCE_FRONT_TO_BACK_MIN = 6;
	var DISTANCE_FRONT_TO_BACK_AVG = 7;
	var DISTANCE_FRONT_TO_BACK_MAX = 8;
	var DISTANCE_BACK_TO_FRONT_MIN = 9;
	var DISTANCE_BACK_TO_FRONT_AVG = 10;
	var DISTANCE_BACK_TO_FRONT_MAX = 11;
}
