name: Linux CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: true

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq \
          libegl1-mesa-dev libgl1-mesa-dev libdbus-1-dev libibus-1.0-dev libdbus-1-dev libdecor-0-dev libudev-dev libgbm-dev libdrm-dev \
          libx11-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbcommon-dev libxcursor-dev libxrandr-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxxf86vm-dev \
          libpulse-dev libasound2-dev libpipewire-0.3-dev \
          g++-multilib gcc-multilib
          haxelib git hxcpp https://github.com/FunkinCrew/hxcpp --quiet
          haxelib install format --quiet
          haxelib install hxp --quiet
          haxelib dev lime $GITHUB_WORKSPACE

      - name: Rebuild Lime
        run: |
          rm -rf ./ndll
          mkdir ./ndll

          haxelib run lime rebuild hxcpp
          haxelib run lime rebuild linux -64 -eval -nocolor -nocffi
          # haxelib run lime rebuild linux -32 -eval -nocolor -nocffi

      - uses: actions/upload-artifact@v7.0.0
        with:
          name: Linux-NDLL
          path: ndll
          if-no-files-found: error
