name: Mac CI
on: workflow_dispatch

env:
  HAXE_VERSION: 4.3.5

jobs:
  mac:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}
      - name: Install Haxe dependencies
        run: |
          curl -LO https://github.com/HaxeFoundation/hxcpp/releases/download/v4.3.66/hxcpp-4.3.66.zip
          haxelib install ./hxcpp-4.3.66.zip --quiet
          haxelib install format --quiet
          haxelib install hxp --quiet
      - name: Configure Lime
        run: haxelib dev lime ${{ github.workspace }}
      - name: Rebuild Lime
        run: |
          # haxelib run lime rebuild mac -32 -release -nocolor -nocffi -eval
          haxelib run lime rebuild mac -64 -release -nocolor -nocffi -eval
      # - name: Upload Artifact (x86)
        # uses: actions/upload-artifact@v3
        # with:
          # name: Mac-NDLL
          # path: |
            # ndll/Mac/
            # !**/.gitignore
          # if-no-files-found: error
      - name: Upload Artifact (x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: Mac64-NDLL
          path: |
            ndll/Mac64/
            !**/.gitignore
          if-no-files-found: error
  macarm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}
      - name: Install Haxe dependencies
        run: |
          curl -LO https://github.com/HaxeFoundation/hxcpp/releases/download/v4.3.66/hxcpp-4.3.66.zip
          haxelib install ./hxcpp-4.3.66.zip --quiet
          haxelib install format --quiet
          haxelib install hxp --quiet
          haxelib dev lime $GITHUB_WORKSPACE
      - name: Configure Lime
        run: haxelib dev lime ${{ github.workspace }}
      - name: Rebuild Lime
        run: haxelib run lime rebuild mac -arm64 -release -nocolor -nocffi -eval -D HXCPP_ARM64
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MacArm64-NDLL
          path: |
            ndll/MacArm64/
            !**/.gitignore
          if-no-files-found: error
